name: silent_caller
description: A safety-focused app for silent communication using tap patterns
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Sensors and Device Features
  sensors_plus: ^3.1.0
  vibration: ^1.8.4
  device_info_plus: ^9.1.1
  
  # Communication
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  
  # Security and Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Background Services
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.3.0
  
  # SMS (for offline functionality)
  telephony: ^0.2.0
  
  # UI Components
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 